<?php

namespace Fredb\AdminBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * JEntityItemRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class JEntityItemRepository extends EntityRepository
{

    
    
    
}